#!/bin/bash

# Home Network Guardian - Remote Quick Reference
# Quick commands for managing Guardian on Sammy

echo "🛡️  Home Network Guardian - Remote Quick Commands"
echo "================================================="
echo ""
echo "📊 MANAGEMENT COMMANDS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Status & Info:"
echo "  ./remote_cmd.sh status      # Show network status"
echo "  ./remote_cmd.sh devices     # List all known devices"
echo "  ./remote_cmd.sh alerts      # Show recent alerts"
echo "  ./remote_cmd.sh logs        # View live logs"
echo ""
echo "Operations:"
echo "  ./remote_cmd.sh scan        # Scan network for devices"
echo "  ./remote_cmd.sh restart     # Restart the service"
echo "  ./remote_cmd.sh stop        # Stop monitoring"
echo "  ./remote_cmd.sh start       # Start monitoring"
echo ""
echo "🔧 SETUP COMMANDS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Initial Deployment:"
echo "  ./deploy_remote.sh user@sammy                    # Deploy everything"
echo "  ./deploy_remote.sh user@sammy /custom/path       # Deploy to custom path"
echo ""
echo "Manual Setup:"
echo "  ssh user@sammy"
echo "  cd home-network-security"
echo "  source venv/bin/activate"
echo "  python guardian.py setup    # Configuration wizard"
echo "  python guardian.py init     # Initialize database"
echo "  python guardian.py daemon   # Start monitoring"
echo ""
echo "🔍 TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Check Connection:"
echo "  ssh user@sammy 'echo ✅ Connection working'"
echo ""
echo "Service Status:"
echo "  ssh user@sammy 'sudo systemctl status guardian'"
echo ""
echo "Error Logs:"
echo "  ssh user@sammy 'sudo journalctl -u guardian -n 50'"
echo ""
echo "Network Interface:"
echo "  ssh user@sammy 'ip addr'    # List available interfaces"
echo ""
echo "Router Connectivity:"
echo "  ssh user@sammy 'ping 192.168.1.1'"
echo ""
echo "📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Full Deployment Guide:"
echo "  → REMOTE_DEPLOYMENT.md"
echo ""
echo "Quick Setup for Sammy:"
echo "  → REMOTE_SETUP_GUIDE.md"
echo ""
echo "Initial Configuration:"
echo "  → QUICKSTART.md"
echo ""
echo "Complete Documentation:"
echo "  → README.md"
echo ""
echo "🎯 TYPICAL WORKFLOW"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Deploy to Sammy:"
echo "   ./deploy_remote.sh user@sammy"
echo ""
echo "2. Configure:"
echo "   ssh user@sammy"
echo "   cd home-network-security && source venv/bin/activate"
echo "   python guardian.py setup"
echo ""
echo "3. Initialize:"
echo "   python guardian.py init"
echo "   python guardian.py scan"
echo ""
echo "4. Start monitoring:"
echo "   python guardian.py daemon"
echo "   (Or setup as systemd service)"
echo ""
echo "5. Check status from home computer:"
echo "   ssh user@sammy \"cd home-network-security && source venv/bin/activate && python guardian.py status\""
echo ""
echo "5. Setup automated service (optional):"
echo "   sudo nano /etc/systemd/system/guardian.service"
echo "   (Copy config from REMOTE_DEPLOYMENT.md)"
echo ""
echo "✅ You're ready to monitor remotely!"
echo ""
